name: "Continuous Integrations"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    uses: ./.github/workflows/reusable_setup.yml

  lint:
    needs: 'setup'
    uses: ./.github/workflows/reusable_lint.yml

  build:
    needs: 'setup'
    uses: ./.github/workflows/reusable_build.yml

  verify-plugin-android:
    needs: ['setup', 'lint', 'build']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Verify Android'
        run: npm run verify:android

  verify-plugin-ios:
    needs: ['setup', 'lint', 'build']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Verify iOS'
        run: npm run verify:ios
  
  build-example-app-android:
    needs: ['verify-plugin-ios', 'verify-plugin-android']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Prepare example app'
        uses: ./.github/actions/prepare-example-app
      - name: 'Build Android example app'
        working-directory: ./example-app/android
        run: ./gradlew clean assembleDebug
    
  build-example-app-ios:
    needs: ['verify-plugin-ios', 'verify-plugin-android']
    runs-on: 'macos-15'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: 'Setup Tools'
        uses: ./.github/actions/setup-tools
      - name: 'Prepare example app'
        uses: ./.github/actions/prepare-example-app
      - name: 'Build iOS example app'
        working-directory: ./example-app/ios/App
        run: xcodebuild clean build -workspace App.xcworkspace -scheme App CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
