name: Publish Capacitor Plugin to CocoaPods Trunk

on:
  workflow_call:
    secrets:
      COCOAPODS_TRUNK_TOKEN:
        required: true
      CAP_GH_RELEASE_TOKEN:
        required: true
  workflow_dispatch:

jobs:
  publish-ios:
    runs-on: macos-15
    if: github.ref == 'refs/heads/main'
    timeout-minutes: 30
    steps:
      - run: sudo xcode-select --switch /Applications/Xcode_16.app
      - run: xcrun simctl list > /dev/null
      - run: xcodebuild -downloadPlatform iOS
      - uses: actions/setup-node@v6
        with:
          node-version: 22
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.CAP_GH_RELEASE_TOKEN }}
      - name: Pull latest commits
        run: git pull origin main
      - name: Install Cocoapods
        run: | 
          gem install cocoapods
      - name: Grant execute permission for publishing script
        run: chmod +x ./scripts/publish-ios.sh
      - name: Deploy to Cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          ./scripts/publish-ios.sh
